# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/src/LevelChooseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LevelChooseWindow(object):
    def setupUi(self, LevelChooseWindow):
        LevelChooseWindow.setObjectName("LevelChooseWindow")
        LevelChooseWindow.resize(416, 188)
        self.centralwidget = QtWidgets.QWidget(LevelChooseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxLevel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxLevel.setObjectName("comboBoxLevel")
        self.gridLayout.addWidget(self.comboBoxLevel, 0, 0, 1, 2, QtCore.Qt.AlignTop)
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout.addWidget(self.StartButton, 1, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.HelpButton = QtWidgets.QPushButton(self.centralwidget)
        self.HelpButton.setObjectName("HelpButton")
        self.gridLayout.addWidget(self.HelpButton, 1, 1, 1, 1, QtCore.Qt.AlignBottom)
        LevelChooseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LevelChooseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        LevelChooseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LevelChooseWindow)
        self.statusbar.setObjectName("statusbar")
        LevelChooseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LevelChooseWindow)
        QtCore.QMetaObject.connectSlotsByName(LevelChooseWindow)

    def retranslateUi(self, LevelChooseWindow):
        _translate = QtCore.QCoreApplication.translate
        LevelChooseWindow.setWindowTitle(_translate("LevelChooseWindow", "Choose Level"))
        self.StartButton.setText(_translate("LevelChooseWindow", "Start"))
        self.HelpButton.setText(_translate("LevelChooseWindow", "Help"))
